# Generated by Django 3.1.7 on 2021-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_liked', models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='unlike', max_length=8)),
            ],
        ),
    ]
