# Generated by Django 3.1.7 on 2021-03-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=100)),
                ('time', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
