# Generated by Django 3.1.7 on 2021-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpro', '0002_auto_20210325_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='postds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='postdata',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
