# Generated by Django 3.1.7 on 2021-03-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpro', '0003_auto_20210326_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postdata',
        ),
    ]
